# Generated by Django 3.2.19 on 2023-06-17 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('biografia', models.TextField(blank=True)),
                ('tipo_perfil', models.CharField(choices=[('1', 'Productor/a'), ('2', 'Artista')], max_length=1)),
                ('imagen_perfil', models.ImageField(blank=True, upload_to='perfiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('entradas_disponibles', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='eventos')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
