# Generated by Django 3.2.19 on 2023-06-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='evento',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
