# Generated by Django 3.2.19 on 2023-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='img/perfiles/default.png', upload_to='img/perfiles'),
        ),
    ]
