# Generated by Django 3.2.19 on 2023-06-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, default='static/img/eventos/default.png', upload_to='static/img/eventos/<django.db.models.fields.related.ForeignKey>'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='static/img/perfiles/default.png', upload_to='static/img/perfiles'),
        ),
    ]
