# Generated by Django 3.2.19 on 2023-06-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_evento_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='biografia',
            new_name='descripcion',
        ),
    ]
