# Generated by Django 4.2.2 on 2023-06-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20230618_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, default='static/img/eventos/default.png', upload_to='static/img/eventos/'),
        ),
    ]
