# Generated by Django 4.2.2 on 2023-06-16 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crud', '0005_rename_biografia_evento_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.CharField(blank=True, max_length=1000)),
                ('tipo_perfil', models.CharField(choices=[('1', 'Productor/a'), ('2', 'Artista')], max_length=1)),
                ('imagen_perfil', models.ImageField(blank=True, upload_to='perfiles')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
